---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo

  tasks:
  
  - name: Update repositories cache 
    apt:
      update_cache: yes

  - name: install ntp
    apt: 
      name: ntp
      state: present
      update_cache: yes
  
  - name: Install ufw package
    apt:
      name: ufw
      state: present

  - name: Set default ufw rules to allow all outgoing connections
    ufw:
      policy: allow

  - name: Set default ufw rules to deny all incoming connections and enable ufw
    ufw:
      policy: deny
   
  - name: Allow ssh from ansible server 
    ufw:
      rule: allow 
      port: 22
      src: "{{ ansibleIP }}" 

  - name: Set logging
    ufw: 
      logging: 'on'

  - name: Allow everything and enable UFW
    ufw:
      state: enabled

  - name: Install fail2ban package
    apt:
      name: fail2ban
      state: present